[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri Application"
authors = ["Your Name <you@example.com>"]
build = "build.rs"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["api-all"] }

[build-dependencies]
tauri-build = "1"

